#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/amelorate/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

compton &
feh --bg-max '/home/amelorate/Pictures/Wallpapers/1518565865621.jpg' --bg-max '/home/amelorate/Pictures/Wallpapers/1521555464268.png'
~/Documents/wmmp/WMmp &
AlsaMixer.app -2 Capture &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/amelorate/.fluxbox/log"
